name: CI/CD for One-Day Tour Planner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint, Test, and Deploy
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:latest
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: "neo4j/your_password_here"

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 4: Lint with Flake8
    - name: Lint with Flake8
      run: |
        source venv/bin/activate
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Step 5: Run tests
    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest tests/

    # Step 6: Deploy (Optional)
    - name: Deploy to Heroku (Optional)
      if: success()
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: one-day-tour-planner
        heroku_email: your-email@example.com
